name: PR Check

# 1. Trigger piple line when we have a PR into branch main
on:
  pull_request:
    branches:
      - main

# 2. Declaration Working Job
jobs:
  validate-code:
    # provide a virtual server running by Linux
    runs-on: Ubuntu-latest

    # 3. Steps: The steps to execute sequentially on that virtual server.
    steps:
      # Step 1: Clone code from repo into virtual Runner
      - name: Checkout source code
        uses: actions/checkout-@v4

      # Step 2: Install env (Node JS)
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependences
      - name: Install dependences
        # Must use `npm ci` instead of `npm install` in the CI env to ensure the exact versions specified in package-lock.json are installed
        run: npm ci

      # Step 4: Check TS typing
      - name: Type check
        run: npx tsc --noEmit

      # Step 5: Check Format Code
      - name: Run Linter
        run: npm run lint

      # Step 6: Try build to ensure application not crash
      - name: Build Next.js App
        run:  npm run build
