name: PR Check

on:
  pull_request:
    branches: ['main', 'master']

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependences
        run: |
          corepack enable
          yarn install --immutable

      - name: Type check
        run: yarn typecheck

      - name: Run Linter
        run: yarn lint

      - name: Build NextJS App
        run: yarn build
